name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels: ["feature", "enhancement"]
  - title: "Fixes"
    labels: ["bug", "fix"]
  - title: "Chores"
    labels: ["chore"]
  - title: "Docs"
    labels: ["docs"]
  - title: "Performance"
    labels: ["performance"]
  - title: "Tests"
    labels: ["test"]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch", "fix", "chore", "docs", "test", "performance"]
template: |
  ## Changes
  $CHANGES
