filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/ecommerce/*.log
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata: {}
  - add_cloud_metadata: {}
