{
 "title": "Microservices - Technical Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Service",
    "query": "label_values(http_server_requests_seconds_count, application)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(application)(rate(http_server_requests_seconds_count{application=~\"$application\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\",application=~\"$application\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=~\"$application\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, application) (rate(http_server_requests_seconds_bucket{application=~\"$application\"}[5m])))"
    }
   ]
  },
  {
   "title": "JVM Heap Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(application)(jvm_memory_used_bytes{area=\"heap\",application=~\"$application\"})"
    }
   ]
  },
  {
   "title": "Circuit breaker failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(application)(rate(resilience4j_circuitbreaker_calls_seconds_count{kind=\"failed\",application=~\"$application\"}[5m]))"
    }
   ]
  },
  {
   "title": "Up / Down",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (up{job=~\"$application\"})"
    }
   ]
  }
 ]
}